name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload `website` folder
        uses: actions/upload-pages-artifact@v2
        with:
          path: website

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
